list = [
    [
        0,
        0,
        {
            "qty": 1,
            "price_unit": 39.4,
            "price_subtotal": 39.4,
            "price_subtotal_incl": 39.4,
            "discount": 0,
            "product_id": 24,
            "tax_ids": [[6, False, []]],
            "id": 1,
            "pack_lot_ids": [],
            "description": "",
            "full_product_name": "Conference Chair (Aluminium)",
            "price_extra": 0,
            "price_manually_set": False,
            "washing_stage": "Wash Only",
            "washing_amount": "10",
            "washing_id": "1",
        },
    ],
    [
        0,
        0,
        {
            "qty": 1,
            "price_unit": 33,
            "price_subtotal": 33,
            "price_subtotal_incl": 33,
            "discount": 0,
            "product_id": 23,
            "tax_ids": [[6, False, []]],
            "id": 2,
            "pack_lot_ids": [],
            "description": "",
            "full_product_name": "Conference Chair (Steel)",
            "price_extra": 0,
            "price_manually_set": False,
            "washing_stage": "Iron Only",
            "washing_amount": "15",
            "washing_id": "2",
        },
    ],
    [
        0,
        0,
        {
            "qty": 1,
            "price_unit": 70,
            "price_subtotal": 70,
            "price_subtotal_incl": 70,
            "discount": 0,
            "product_id": 5,
            "tax_ids": [[6, False, []]],
            "id": 3,
            "pack_lot_ids": [],
            "description": "",
            "full_product_name": "Office Chair",
            "price_extra": 0,
            "price_manually_set": False,
            "washing_stage": "Wash and Iron Both",
            "washing_amount": "30",
            "washing_id": "3",
        },
    ],
]

for rec in list:
    print(rec[2]['washing_id'])